
trigger:
- master
variables:
  python.version: '3.7.6'

pool: myAgentPool

stages:
- stage: deploy_terraform
  displayName: provision infrastructure  
  jobs: 
  - deployment: deploy_terraform
    continueOnError: false
    environment: 'EvnP3'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            # - task: TerraformInstaller@0
            #   displayName: 'install terraform'
            #   inputs:
            #     terraformVersion: 'latest'
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here
                  echo 'Hello world'
  
