name: myAgentPool
trigger:
- master

pool: 
   vmImage: ubuntu-latest
   name: MyAget

jobs:
   displayName: Deploy to VM
   environment: 
      name: EvnP3
      resourceType: VirtualMachine
   strategy:
      runOnce:
         deploy:   
            steps:
               - script: echo "Hello world"