name: myAgentPool
trigger:
- master

pool: 
   vmImage: ubuntu-latest
   name: MyAgent

stages:
- stage: deploy_terraform
  displayName: provision infrastructure  
  jobs: 
  - deployment: deploy_terraform
    continueOnError: false
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self           
            - task: TerraformInstaller@0
              displayName: 'install terraform'
              inputs:
                terraformVersion: 'latest'
            - task: Bash@3
              displayName: init
              inputs:
                targetType: 'inline'
                script: |
                  echo "hi"
