name: myAgentPool
trigger:
- master

pool: 
   vmImage: ubuntu-latest
   name: MyAgent

stages:
- stage: Build
  displayName: Deploy
  jobs:
  - deployment: Deploy_to_VM
    environment: 
      name: 'EvnP3'
      resourceType: VirtualMachine
    strategy:
      runOnce:
         deploy:   
            steps:
               - script: echo "Hello world"