# name: Azure Pipelines
trigger:
- master

pool: 
   vmImage: ubuntu-latest

jobs:
   displayName: Deploy to VM
   environment: 
      name: EvnP3
      resourceType: VirtualMachine
   strategy:
      runOnce:
         deploy:   
            steps:
               - script: echo "Hello world"